### ISSUE TITLE
How to automatically generate schema.yaml?

### ISSUE THREAD

**Issue by Marsman1996** [hgarrereyn/GraphFuzz#3]
Hi! Your work GraphFuzz is impressive, it is a very effective and promising method to test API functions.

The `gfuzz` could infer a schema from Doxygen xml by `gfuzz schema infer doxygen_xml, output`.
But how about the projects without a doxygen document?

Thanks for any reply!

**Comment by hgarrereyn** [comment]
Hi, the Doxygen extractor is very experimental currently. The way it works is it creates a [template Doxyfile](https://github.com/hgarrereyn/GraphFuzz/blob/b0974b2d5def7fd675f8402326d64b2deb8bd58c/cli/gfuzz/commands/doxygen/docker/in/Doxyfile.template) for a source directory and then it runs `doxygen` inside of docker. Currently we just use a simple Doxyfile template:

```doxyfile
EXTRACT_ALL = YES
EXTRACT_STATIC = YES
EXTRACT_LOCAL_CLASSES = YES
EXTRACT_LOCAL_METHODS = YES

INPUT = {input}
RECURSIVE = true

GENERATE_XML = YES
XML_PROGRAMLISTING = NO
MACRO_EXPANSION = YES

GENERATE_HTML = NO
GENERATE_LATEX = NO
GENERATE_RTF = NO
GENERATE_MAN = NO
GENERATE_AUTOGEN_DEF = NO
GENERATE_PERLMOD = NO
```

where `{input}` gets replaced with the path to the source directory.

So this tool will work on projects that don't have an existing `Doxyfile` (since we build our own). For example, you can look at the [ex_auto_cpp experiment](https://github.com/hgarrereyn/GraphFuzz/tree/b0974b2d5def7fd675f8402326d64b2deb8bd58c/experiments/ex_auto_cpp)

---

In general though, it's not possible to automatically extract _every_ struct and method flawlessly unless you are working on a small, toy example like above. For instance, with a function like:

```cpp
void handleRawData(void *)
```

it's really not possible to know how to handle that argument. Or if you have something like:

```cpp
void setAlpha(float a) {
    assert(0 <= a < 1);
    ...
}
```

you can automatically fuzz this, but you will be wasting a lot of time hitting the assert.

---

During some of our experiments, I found a good approach was to use the doxygen extractor to generate a very large `raw_schema.yaml` that contained all the structs/enums/methods... Then I went through and copy-pasted the parts I wanted to test and made changes as necessary so the schema was correct.

**Comment by Marsman1996** [comment]
Thanks for your quick reply!

I follow the guide and successfully generate the raw schema. 

However, I have to install `lxml` package manually in the docker, otherwise the infer process could be wrong:
```
root@b3a740cc84e0:/workdir# gfuzz schema infer ./in/doxygen_output/xml ./in/auto_schema.yaml
[!] Could not parse doxygen output. Make sure there is an "index.xml" file in the target directory.
root@b3a740cc84e0:/workdir# pip3 install lxml
Collecting lxml
  Downloading https://files.pythonhosted.org/packages/fd/9c/d0bbb2ac23561738629cf6a04c660f721774905669b02bb764237c8bd48c/lxml-4.8.0-cp36-cp36m-manylinux_2_5_x86_64.manylinux1_x86_64.whl (5.6MB)
    100% |################################| 5.6MB 229kB/s 
Installing collected packages: lxml
Successfully installed lxml-4.8.0
root@b3a740cc84e0:/workdir# gfuzz schema infer ./in/doxygen_output/xml ./in/auto_schema.yaml
Parsing structs...: 100%|##############################################################################################################################################| 2/2 [00:00<00:00, 138.23it/s]
Parsing classes...: 0it [00:00, ?it/s]
Parsing files...: 100%|################################################################################################################################################| 4/4 [00:00<00:00, 434.98it/s]
[*] Generated a schema with 4 items.
```

Besides, the path in README of `ex_auto_cpp` is also wrong.

**Comment by hgarrereyn** [comment]
Hi, thanks for finding this issues! I've pushed a commit that should clarify the ex_auto_cpp README a bit more. I also added `lxml` as a dependency to `gfuzz` as that was missing and is required for `gfuzz schema infer`.

Currently `gfuzz doxygen` actually spawns a new docker container to run `doxygen` so you have to run it on your host machine (or start nesting docker images). So the intention is that you run the `make_schema.sh` script outside of the docker container (I've added some notes in the readme to explain this).

It would be nice to do the full series of commands `gfuzz doxygen`, `gfuzz schema infer`, `gfuzz gen`... inside the example docker image as well so that could be something to put on the todo list. Maybe a command line switch on `gfuzz doxygen` to select between spawning a new docker image and running `doxygen` locally...

Hopefully this helps answer your questions, let me know if you run into any other usage issues!
